### ISSUE TITLE
Anki on Ubuntu 24.04

### ISSUE THREAD

**Issue by kxygk** [vonpetersenn/Pleco-to-Anki#14]
I get the following error when I add `Pleco to Anki` (using the code or the file)

I'm running Anki from the Ubuntu repository, on version 24.04 LTS

````
When loading 'Pleco to Anki':
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 80, in loadAddons
    __import__(dir)
  File "/home/kxygk/.local/share/Anki2/addons21/pleco_to_anki/__init__.py", line 4, in <module>
    from aqt.utils import qconnect, showInfo, QAction
ImportError: cannot import name 'qconnect' from 'aqt.utils' (/usr/share/anki/aqt/utils.py)
````

Maybe I need to install some python library, but I'm unclear which one. `qconnect` is not a library and seems to be part of qpython (a port of Python to Android?)

(As I understand things.. this plug in is for the desktop version of Anki - b/c AnkiDroid doesn't seem to have  a plug in interface)

**Comment by kxygk** [comment]
Seems the issue is Ubuntu's Anki version - `2.1.15`

With the latest Anki version from the official Anki website this error does not occur

A note in the documentation would be useful! :))
